### ISSUE TITLE
Question: Will it support sublime text 3 soon?

### ISSUE THREAD

**Issue by alexkvazos** [smpanaro/sublime-spotify#1]
I really enjoyed this plugin on sublime text 2 and I would like to know if it will be updated to support the new sublime text 3. Thanks.

**Comment by smpanaro** [comment]
Actually, I rewrote it for ST3 yesterday. It still needs a little more testing, but I should be releasing it soon.

**Comment by alexkvazos** [comment]
Sounds good! Thanks.
