### ISSUE TITLE
Doesn't seem like ST3 is reading it.

### ISSUE THREAD

**Issue by alexkvazos** [smpanaro/sublime-spotify#2]
I wasn't able to install the plugin from Package Control so I cloned the repository into
/Users/alexkvazos/Library/Application\ Support/Sublime\ Text\ 3

My package settings dropdown does show sublime-spotify but command palette does not show any command related to the plugin.

**Comment by smpanaro** [comment]
I'm still waiting for approval to release on Package Control, but will probably get that soon.
 In the meantime, I think you cloned it into the wrong directory. It needs to be in the Packages directory.

This command works for me:
`git clone git@github.com:smpanaro/sublime-spotify.git /Users/Steve/Library/Application\ Support/Sublime\ Text\ 3/Packages/SublimeSpotify`

If you're still having trouble, copy/paste the contents of your Sublime console here for me. (View -> Show Console, or `Control + ``)

**Comment by alexkvazos** [comment]
I just changed the folder name to SublimeSpotify and it worked. Does the plugin needs the folder to be called exactly like it?

**Comment by smpanaro** [comment]
Actually, it absolutely does need to be named that for everything to work.
That's a bug that I will fix ASAP. Thanks!

**Comment by smpanaro** [comment]
@AlexKvazos FYI, you will need to rename the folder from "SublimeSpotify" to "Spotify" if you manually update again. Though, I suggest switching to Package Control once it is available.
